/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// sidebar: [{ dirName: '.', type: 'autogenerated' }]

	// But you can create a sidebar manually
	sidebar: [
		'intro',
		{
			type: 'category',
			label: 'Getting started',
			items: [
				'getting-started/concepts',
				'getting-started/installation',
				'getting-started/aws-cross-account-role',
				'getting-started/hello-world'
			]
		},
		{
			type: 'category',
			label: 'How it works',
			items: [
				'how-it-works/alert-lifecycle',
				'how-it-works/under-the-hood',
				'how-it-works/putting-it-together'
			]
		},

		{
			type: 'category',
			label: 'Guides',
			items: [
				{
					type: 'category',
					label: 'Vendor Setup',
					items: [
						'guides/vendor-setup/security-hub/setup',
						'guides/vendor-setup/prisma-cloud/setup'
					]
				},
				{
					type: 'category',
					label: 'Operations',
					items: ['guides/ops/updating-dassana']
				},
				{
					type: 'category',
					label: 'Workflow',
					items: [
						'guides/workflow-authoring/normalize',
						'guides/workflow-authoring/resource-priority',
						'guides/workflow-authoring/contextualize'
					]
				},
				{
					type: 'category',
					label: 'Actions',
					items: ['guides/workflow-authoring/action']
				}
			]
		},
		'support'
	]
}
