schema: 1
type: policy-context

id: aks-cluster-http-application-routing-is-enabled
name: Enabling HTTP application routing may allow applications deployed in AKS to be publically accessible
labels:
  - contextualization

csp: azure
service: Microsoft.Kubernetes
resource-type: Operations

class: risk
subclass: config
category: visibility
subcategory: hygiene

filters:
  - vendor: prisma-cloud
    policies:
      - 0429670c-5d2d-4d0f-ab33-59eb5e000305
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "0429670c-5d2d-4d0f-ab33-59eb5e000305"

risk-config:
  default-risk: low
