name: Publish Unit Test Coverage
on:
  push:
    paths:
      - "engine/**"
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@v1
        with:
          allowed-endpoints: 
            coveralls.io:443
            github.com:443
            jitpack.io:443
            repo.maven.apache.org:443
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: |
          cd engine
          mvn --no-transfer-progress --batch-mode test jacoco:report coveralls:report
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
